name: 3-Tier-Terraform-CI
on: 
  pull_request:
jobs:

  Pre-Test:
    strategy:
      matrix:
        environment: [dev, stg, prod]
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
      
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::954976311612:role/3-tier-terraform-cicd
          aws-region: us-east-1

      - name: Terraform init
        working-directory: terraform
        run: terraform init -lock-timeout=300s

      - name: Terraform create & select workspace
        working-directory: terraform
        run: |
          terraform workspace select ${{matrix.environment}} || terraform workspace new ${{matrix.environment}}

      - name: Terraform Validate 
        working-directory: terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -out=tfplan-${{matrix.environment}}

      - name: upload Artifact
        uses: actions/upload-artifact@v4
        with:
          retention-days: 2
          name: tfplan-${{matrix.environment}}
          path: terraform/tfplan-${{matrix.environment}}


  