name: Terraform Destroy
on: 
  push:
    branches:
      - main
jobs:
  terraform-Destroy-dev:
    runs-on: ubuntu-latest
    environment: des
    permissions:
      id-token: write
      contents: read
  
    steps:
      - name: checkout-repo 
        uses: actions/checkout@v4
      
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::954976311612:role/CI-CD_Terraform
          aws-region: us-east-1

      - name: terraform init
        working-directory: terraform
        run: terraform init

      - name: Terraform create & select workspace
        working-directory: terraform
        run: |
          terraform workspace select dev || terraform workspace new dev

      - name: Terraform Destroy
        working-directory: terraform
        run: terraform destroy -auto-approve


  terraform-Destroy-stg:
    needs: terraform-Destroy-dev
    runs-on: ubuntu-latest
    environment: des
    permissions:
      id-token: write
      contents: read
  
    steps:
      - name: checkout-repo 
        uses: actions/checkout@v4
      
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::954976311612:role/CI-CD_Terraform
          aws-region: us-east-1

      - name: terraform init
        working-directory: terraform
        run: terraform init

      - name: Terraform create & select workspace
        working-directory: terraform
        run: |
          terraform workspace select stg || terraform workspace new stg

      - name: Terraform Destroy
        working-directory: terraform
        run: terraform destroy -auto-approve

  terraform-Destroy-prod:
    needs: terraform-Destroy-stg
    runs-on: ubuntu-latest
    environment: des
    permissions:
      id-token: write
      contents: read
  
    steps:
      - name: checkout-repo 
        uses: actions/checkout@v4
      
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::954976311612:role/CI-CD_Terraform
          aws-region: us-east-1

      - name: terraform init
        working-directory: terraform
        run: terraform init

      - name: Terraform create & select workspace
        working-directory: terraform
        run: |
          terraform workspace select prod || terraform workspace new prod

      - name: Terraform Destroy
        working-directory: terraform
        run: terraform destroy -auto-approve

  